### PR TITLE
Fix syntax errors with latests yeoman and NodeJS LTS versions

### PR DESCRIPTION
**Pull request by NiklasMerz**
Hello,

I just installed the generator and got some syntax error with the latest Yeoman and NodeJS versions:

```
yo --version
2.0.0

node -v
v6.11.2
```

/usr/lib/node_modules/generator-beamng-app/generators/app/index.js:6
var BeamngAppGenerator = yeoman.Base.extend({
                                    ^

```
TypeError: Cannot read property 'extend' of undefined
    at Object.<anonymous> (/usr/lib/node_modules/generator-beamng-app/generators/app/index.js:6:37)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.get [as beamng-app:app] (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:38:27)
    at Store.get (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:61:39)
```
/usr/lib/node_modules/generator-beamng-app/generators/app/index.js:7
  promptUserDialog: function () {
                  ^

```
SyntaxError: Unexpected token :
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.get [as beamng-app:app] (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:38:27)
```

.... and some other.

I was able to get the generator running for me with changing the syntax to more current ECMA standard syntax. I have no idea if this is the perfect solution, because I have never worked with yeoman generators before, but this could help others with these problems.

### CODE REVIEW

**Review by Saniamos — APPROVED** [review]
There seem to have been some changes in the api, since the the generator was written. Your changes look very good :-)
Thank you very much for taking the time and submitting your fixes!

**Comment by NiklasMerz** [comment]
Nice to see this merged.

**Comment by tdev** [comment]
Thanks again, and sorry for the delay! :)

**Comment by NiklasMerz** [comment]
You are welcome. No need for apollogies. Fxing this was fun :-)

**Comment by NiklasMerz** [comment]
I just tried my luck building a BeamNG mod again and this issue is still there in the version from NPM. Would you mind updating the NPM version?

**Pull request merged**
